# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  Configuration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core SDK"
    inputs:
      packageType: "sdk"
      useGlobalJson: true

  - task: DotNetCoreCLI@2
    displayName: "dotnet publish"
    inputs:
      command: "publish"
      projects: "**/*.csproj"
      arguments: "--configuration $(Configuration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: true
      workingDirectory: src

  - script: ls -al $(Build.ArtifactStagingDirectory)
    displayName: "List files in $(Build.ArtifactStagingDirectory)"

  # https://learn.microsoft.com/azure/azure-resource-manager/bicep/quickstart-create-deployment-stacks?tabs=azure-cli%2CCLI&WT.mc_id=DOP-MVP-5001655#create-a-deployment-stack
  - task: AzureCLI@2
    displayName: "Deploy to Azure"
    inputs:
      azureSubscription: "sp-dotnet-linux-australiaeast"
      scriptType: bash
      visibleAzLogin: false
      scriptLocation: "inlineScript"
      inlineScript: |
        az stack group create --name dotnet --resource-group rg-dotnet-linux-australiaeast --template-file main.bicep --action-on-unmanage deleteResources --deny-settings-mode none

  - task: AzureRmWebAppDeployment@5
    displayName: "Deploy to Azure Web App"
    name: deployWebApp
    inputs:
      ConnectionType: "AzureRM"
      azureSubscription: "sp-dotnet-linux-australiaeast"
      appType: "webAppLinux"
      WebAppName: "app-dotnet-linux-australiaeast"
      packageForLinux: "$(Build.ArtifactStagingDirectory)/**/*.zip"

  - pwsh: |
      Invvoke-RestMethod -Uri "$(deployWebApp.AppServiceApplicationUrl)/weatherforecast" -ConnectionTimeoutSeconds 60
    displayName: "Test deployed app"