trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: "Daily midnight"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none

  # https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks?tabs=azure-cli&WT.mc_id=DOP-MVP-5001655#delete-deployment-stacks
  - task: AzureCLI@2
    displayName: "Delete deployment stack"
    inputs:
      azureSubscription: "sp-dotnet-linux-australiaeast"
      scriptType: "bash"
      visibleAzLogin: false
      scriptLocation: "inlineScript"
      inlineScript: |
        az stack group delete --name dotnet --resource-group rg-dotnet-linux-australiaeast --action-on-unmanage deleteResources
